delay: 3600 #second
VNStats:
  - ""
  - "&f&lThông tin Covid-19 &e&lVIỆT NAM"
  - "    &cSố ca nhiễm: {VNCases}&r &f(&7{todayVNCases}&f)"
  - "    &7Tử vong: {VNDeaths} &f(&7{todayVNDeaths}&f)"
  - "    &aĐã khỏi: {VNRecovered} &f(&7{todayVNRecovered}&f)"
  - "    &eĐang điều trị: {VNRecovering} &f({todayVNRecovering}&f)"
  - "_______===&6({date_time})&r===_______"
WStats:
  - "&f&lThông tin Covid-19 &e&lTHẾ GIỚI"
  - "    &cSố ca nhiễm: {WCases} &f(&7{todayWCases}&f)"
  - "    &7Tử vong: {WDeaths} &f(&7{todayWDeaths}&f)"
  - "    &aĐã khỏi: {WRecovered} &f(&7{todayWRecovered}&f)"
  - "    &eĐang điều trị: {WRecovering} &f(&7{todayWRecovering}&f)"
  - "&cHãy thực hiện thông điệp 5K của Bộ Y Tế"
  - "&7Nguồn: &ohttps://covid19.gov.vn/"
sound:
  enable: true
  sound: "ENTITY_PLAYER_LEVELUP"