delay: 3600 #second
VNStats:
  - ""
  - "&f&lThông tin Covid-19 &e&lVIỆT NAM"
  - "    &cSố ca nhiễm: &l{VNCases}&r &f({todayVNCases}&f)"
  - "    &7Tử vong: &f&l{VNDeaths} &f({todayVNDeaths}&f)"
  - "    &aĐã khỏi: &l{VNRecovered} &f({todayVNRecovered}&f)"
  - "    &eĐang điều trị: &l{VNRecovering} {todayVNRecovering}"
  - "_______===&6({date_time})&r===_______"
WStats:
  - "&f&lThông tin Covid-19 &e&lTHẾ GIỚI"
  - "    &cSố ca nhiễm: &l{WCases} {todayWCases}"
  - "    &7Tử vong: &f&l{WDeaths} {todayWDeaths}"
  - "    &aĐã khỏi: &l{WRecovered} {todayWRecovered}"
  - "    &eĐang điều trị: &l{WRecovering}  {todayWRecovering}"
  - "&cHãy thực hiện thông điệp 5K của Bộ Y Tế"
  - "&7Nguồn: &ohttps://covid19.gov.vn/"
sound:
  enable: true
  sound: "ENTITY_PLAYER_LEVELUP"